version: '3'

networks:
  nginx-php7.3:

services:
  nginx: 
    image: nginx:stable-alpine
    container_name: nginx
    ports: 
      - "7000:80"
    volumes:
      - ./src:/var/www/html
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx-php7.3
  
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes: 
      - ./src:/var/www/html
    ports: 
      - "9004:9004"
    networks:
      - nginx-php7.3
    entrypoint: ['php']

  composer:
    image: composer:latest
    container_name: composer
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on: 
      - php
    entrypoint: ['composer']

  npm: 
    image: node:latest
    container_name: npm
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
  